### ISSUE TITLE
Error entering Github access token

### ISSUE THREAD

**Issue by uparix** [bswinnerton/launchbar-github#70]
![image](https://user-images.githubusercontent.com/74161/28249807-357d45a2-6a5d-11e7-8b61-d803a92be4d6.png)

**Comment by bswinnerton** [comment]
Ut oh! Thanks for reporting this, @uparix. How did you go about adding the token? I just tried the process again from the [README.md](https://github.com/bswinnerton/launchbar-github#github-access-token) and it worked.

The rough steps looked something like this:

1. Going to https://github.com/settings/tokens/new
2. Selecting the `repo` and `user` scopes:

    <img width="502" alt="screen shot 2017-07-16 at 1 41 25 pm" src="https://user-images.githubusercontent.com/934497/28249902-85b79c10-6a2c-11e7-89b6-af373ee143d1.png">

3. Clicking the Copy Token button

    <img width="145" alt="screen shot 2017-07-16 at 1 42 05 pm" src="https://user-images.githubusercontent.com/934497/28249904-944dcfb0-6a2c-11e7-9345-f43a5af7dda3.png">

4. Going into the GitHub action

    <img width="668" alt="screen shot 2017-07-16 at 1 42 36 pm" src="https://user-images.githubusercontent.com/934497/28249913-ad79b148-6a2c-11e7-8755-db17c471a842.png">

5. Chose "Set GitHub access token from clipboard"

    <img width="668" alt="screen shot 2017-07-16 at 1 42 39 pm" src="https://user-images.githubusercontent.com/934497/28249917-bd2c92c2-6a2c-11e7-9413-e258dd1b6408.png">

6. Which gave me this:

    ![screen shot 2017-07-16 at 1 42 41 pm](https://user-images.githubusercontent.com/934497/28249918-c4ef2394-6a2c-11e7-8107-520a600731a9.png)

**Comment by bswinnerton** [comment]
My hunch would be that you didn't select the `user` scope when generating the token, which would make this similar to https://github.com/bswinnerton/launchbar-github/issues/37. Is that true @uparix?

**Comment by uparix** [comment]
Just tried it again as given in your instructions, but have the same result. Maybe the only difference is that I have two factor auth enabled. Not sure if that has an effect. I have selected user and repo scope, but it fails on line 38.

**Comment by bswinnerton** [comment]
Does it fail on step 4 or step 5?

**Comment by uparix** [comment]
Step 5

**Comment by uparix** [comment]
I verified that I have the access token in the clipboard

**Comment by uparix** [comment]
Now it worked. I created a new access token. But not sure if that was the issue. I guess you can close this issue.

**Comment by bswinnerton** [comment]
Hmph. That's bizarre, I'm not sure what exactly is causing this, but I'm relatively confident that the issue is happening right [here](https://github.com/bswinnerton/launchbar-github/blob/fb9724462a667246f79ee4f098ca4a58b450df2c/Contents/Scripts/default.js#L395).

I'll try to see if I can find a way to reproduce the issue. In the mean time, it'd be very helpful to see what the response is coming back from GitHub. You can do so by taking these steps:

1. Opening up LaunchBar's Action Editor (I usually do this by invoking LaunchBar and typing "Action"
2. Choosing the GitHub action on the left
3. Enabling Debug Log

    <img width="908" alt="screen shot 2017-07-16 at 3 38 04 pm" src="https://user-images.githubusercontent.com/934497/28250685-d9210c46-6a3c-11e7-8330-dbe18fe36be6.png">

4. Quit and reopen LaunchBar
5. Repeating the steps to try and set the access token
6. Open up the Console application (`/Applications/Utilities/Console.app`)
7. Filter the requests by `action=launchbar-github response=`

From here, you should see the responses coming back from GitHub. As long as there is no sensitive information (like your `token`), it'd be great if you could post that here ❤️.

**Comment by bswinnerton** [comment]
> Now it worked. I created a new access token. But not sure if that was the issue. I guess you can close this issue.

Ah, interesting. Were you reusing an older token, or one that was created just for LaunchBar?

I'm just curious for anyone else who may run into this problem.

**Comment by bswinnerton** [comment]
👋 @uparix,

I've created http://launchbar-github.com to hopefully assist with this sort of thing in the future. By clicking on "Install" on that page, it should go through the GitHub OAuth dance and automatically configure your OAuth token (as of version [v0.2.6](https://github.com/bswinnerton/launchbar-github/releases/tag/v0.2.6)). No more having to go to https://github.com/settings/tokens/new and manually checking checkboxes.

I hope this helps people out in the future.

For now, I'm going to close out this issue since it sounds like you were able to resolve the problem. Thanks again for reporting it, and let me know if you have any feedback!
